Traceback (most recent call last):
  File "/home/shahzar/.local/lib/python3.8/site-packages/nbclient/client.py", line 774, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/home/shahzar/.local/lib/python3.8/site-packages/nbclient/util.py", line 97, in ensure_async
    result = await obj
  File "/home/shahzar/.local/lib/python3.8/site-packages/jupyter_client/channels.py", line 230, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shahzar/.local/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/shahzar/.local/lib/python3.8/site-packages/nbclient/client.py", line 1263, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/shahzar/.local/lib/python3.8/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/shahzar/.local/lib/python3.8/site-packages/nbclient/util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/shahzar/.local/lib/python3.8/site-packages/nbclient/client.py", line 701, in async_execute
    await self.async_execute_cell(
  File "/home/shahzar/.local/lib/python3.8/site-packages/nbclient/client.py", line 1000, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "/home/shahzar/.local/lib/python3.8/site-packages/nbclient/client.py", line 798, in _async_poll_for_reply
    error_on_timeout_execute_reply = await self._async_handle_timeout(timeout, cell)
  File "/home/shahzar/.local/lib/python3.8/site-packages/nbclient/client.py", line 850, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
# HIDDEN
from datascience import *
from prob140 import *
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
import numpy as np
-------------------

